/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import DTO.UsuarioDTO1;
import Dao.UsuarioDAO1;
import Funcionario.Tela_funcionario;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author breno
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
                        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSenha1 = new javax.swing.JPasswordField();
        jNome1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(209, 79, 245));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Sair");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 80, 40));

        jButton5.setBackground(new java.awt.Color(209, 79, 245));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Login");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 80, 40));

        jSenha1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jSenha1.setForeground(new java.awt.Color(209, 79, 245));
        jSenha1.setText("jPasswordField1");
        jSenha1.setBorder(null);
        getContentPane().add(jSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 360, 40));

        jNome1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jNome1.setForeground(new java.awt.Color(209, 79, 245));
        jNome1.setBorder(null);
        jNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNome1ActionPerformed(evt);
            }
        });
        getContentPane().add(jNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 370, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jLabel4.setMaximumSize(new java.awt.Dimension(802, 481));
        jLabel4.setMinimumSize(new java.awt.Dimension(802, 481));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//sair do sistema
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       // verificar se usuario e senha estão no banco de dados,então entra na tela principal
        try{
        String nome,senha;
        nome=jNome1.getText();
        senha=jSenha1.getText();
        UsuarioDTO1 objusuariodto1= new UsuarioDTO1();
        objusuariodto1.setNome(nome);
                objusuariodto1.setSenha(senha);
                UsuarioDAO1 objusuariodao1 = new UsuarioDAO1();
                ResultSet rsusuariodao1= objusuariodao1.autenticacaoUsuario1(objusuariodto1);
                if(rsusuariodao1.next()){
                    Tela_funcionario objtela= new Tela_funcionario();
                    objtela.setVisible(true);
                    dispose();
                }
                else{
                    //usuario e senha não cadastrados no banco de dados,fecha a tela
                               JOptionPane.showMessageDialog(null,"Usuário ou senha inválida");

                }
       }
       catch(SQLException erro){
           JOptionPane.showMessageDialog(null,"Principal"+erro);
           
       }

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNome1ActionPerformed

    /**
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNome1;
    private javax.swing.JPasswordField jSenha1;
    // End of variables declaration//GEN-END:variables
}
