/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Funcionario;

import DTO.CaDTO;
import Dao.CaDao;
import Principal.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */
public class Ca extends javax.swing.JFrame {
//variáveis
 private String Nome,Data,Ex1,Serie,Ex2,Serie2,Ex3,Serie3,Ex4,Serie4,Ex5,Serie5;

    /**
     * Creates new form Ca
     */
    public Ca() {
        initComponents();
                setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jEx1 = new javax.swing.JTextField();
        jSerie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jEx2 = new javax.swing.JTextField();
        jSerie2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jEx3 = new javax.swing.JTextField();
        jSerie3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jEx4 = new javax.swing.JTextField();
        jSerie4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jEx5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSerie5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jData = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 79, 245));
        jLabel3.setText("Série");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jButton2.setBackground(new java.awt.Color(209, 79, 245));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 79, 245));
        jLabel2.setText("Exercício 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jEx1.setBackground(new java.awt.Color(209, 79, 245));
        jEx1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEx1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jEx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 270, -1));

        jSerie.setBackground(new java.awt.Color(209, 79, 245));
        jSerie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSerie.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 79, 245));
        jLabel5.setText("Exercício 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 79, 245));
        jLabel6.setText("Série");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        jEx2.setBackground(new java.awt.Color(209, 79, 245));
        jEx2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEx2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jEx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 270, -1));

        jSerie2.setBackground(new java.awt.Color(209, 79, 245));
        jSerie2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSerie2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSerie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 150, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(209, 79, 245));
        jLabel8.setText("Exercício 3");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(209, 79, 245));
        jLabel9.setText("Série");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        jEx3.setBackground(new java.awt.Color(209, 79, 245));
        jEx3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEx3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jEx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 270, -1));

        jSerie3.setBackground(new java.awt.Color(209, 79, 245));
        jSerie3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSerie3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSerie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 150, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(209, 79, 245));
        jLabel11.setText("Exercício 4");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(209, 79, 245));
        jLabel12.setText("Série");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, -1, -1));

        jEx4.setBackground(new java.awt.Color(209, 79, 245));
        jEx4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEx4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jEx4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 270, -1));

        jSerie4.setBackground(new java.awt.Color(209, 79, 245));
        jSerie4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSerie4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSerie4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 150, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(209, 79, 245));
        jLabel14.setText("Exercício 5");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        jEx5.setBackground(new java.awt.Color(209, 79, 245));
        jEx5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEx5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jEx5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 270, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(209, 79, 245));
        jLabel15.setText("Série");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        jSerie5.setBackground(new java.awt.Color(209, 79, 245));
        jSerie5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSerie5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSerie5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 79, 245));
        jLabel4.setText("Nome");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jCodigo.setBackground(new java.awt.Color(209, 79, 245));
        jCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(jCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 240, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(209, 79, 245));
        jLabel7.setText("Data");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jButton3.setBackground(new java.awt.Color(209, 79, 245));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        jButton1.setBackground(new java.awt.Color(209, 79, 245));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, -1, -1));

        jData.setBackground(new java.awt.Color(209, 79, 245));
        jData.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataActionPerformed(evt);
            }
        });
        getContentPane().add(jData, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //Cadastrar Ficha A
        Nome = jCodigo.getText();
        Data = jData.getText();
        Ex1 = jEx1.getText();
        Serie = jSerie.getText();
        Ex2 = jEx2.getText();
        Serie2 = jSerie2.getText();
        Ex3 = jEx3.getText();
        Serie3 = jSerie3.getText();

        Ex4 = jEx4.getText();
        Serie4 = jSerie4.getText();
        Ex5 = jEx5.getText();
        Serie5 = jSerie5.getText();

        CaDTO objcadto = new CaDTO();
        objcadto.setNome(Nome);
        objcadto.setData(Data);
        objcadto.setEx1(Ex1);
        objcadto.setSerie(Serie);
        objcadto.setEx2(Ex2);
        objcadto.setSerie2(Serie2);
        objcadto.setEx3(Ex3);
        objcadto.setSerie3(Serie3);
        objcadto.setEx4(Ex4);
        objcadto.setSerie4(Serie4);
                objcadto.setEx5(Ex5);
                        objcadto.setSerie5(Serie5);
                        //mensagem pra campos vazios
                        if(jCodigo.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}
if(jData.getText().equals("    -  -  ")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
} 


if(jEx1.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}
if(jSerie.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}
if(jEx2.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}
if(jSerie2.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}
if(jEx3.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}
if(jSerie3.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}
if(jEx4.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}
if(jSerie4.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}
if(jEx5.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}
if(jSerie5.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Campo  obrigatório,o preencha por favor !!","Aviso",JOptionPane.WARNING_MESSAGE);
    return;
}

        CaDao objcadao = new CaDao();
        objcadao.cadastar(objcadto);   
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //voltar pra tela principal
        new Tela_funcionario() .setVisible(true);

        this.dispose();// TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //sair do sistema
        System.exit(0);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataActionPerformed

    /**
     */
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */

 /* Create and display the form */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JFormattedTextField jData;
    private javax.swing.JTextField jEx1;
    private javax.swing.JTextField jEx2;
    private javax.swing.JTextField jEx3;
    private javax.swing.JTextField jEx4;
    private javax.swing.JTextField jEx5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jSerie;
    private javax.swing.JTextField jSerie2;
    private javax.swing.JTextField jSerie3;
    private javax.swing.JTextField jSerie4;
    private javax.swing.JTextField jSerie5;
    // End of variables declaration//GEN-END:variables
}
